### ISSUE TITLE
Add platoon logos to division index

### ISSUE THREAD

**Issue by flashadvocate** [ClanAODDev/tracker_v3#310]
Platoons can have logos set, but the only place they are displayed is on the division structures. We should tweak the display so that these logos (if set) can show up in the tracker interface.

Concept image: 

![image](https://github.com/ClanAODDev/tracker_v3/assets/7848492/a4100e51-5e83-4d5c-9a53-19a10ab17d45)

**Comment by bashtech** [comment]
How does this look? I wasn't sure where to put the "X Assigned".

![image](https://github.com/ClanAODDev/tracker_v3/assets/112572/dc6ee21c-0414-42b2-ad8a-fcdaa5241bf5)

1b7d1d0b8944239fc6ed85f0a6a68af07f504504

**Comment by flashadvocate** [comment]
That looks great! Honestly we can probably out the count next to the name since it’s already a badge

**Comment by bashtech** [comment]
Version 2. I think I prefer this alignment. 

![image](https://github.com/ClanAODDev/tracker_v3/assets/112572/6d892709-a5e0-44df-9537-1fe51a4cbc91)
