### ISSUE TITLE
Division structure edits for new divisions

### ISSUE THREAD

**Issue by flashadvocate** [ClanAODDev/tracker_v3#335]
There's a bit of a chicken and egg issue with division structure changes for newly created divisions. When you go to the "generate division structure" page, it wants to render the twig code even if none is set. We should probably go straight to the editor from the navigation rather than trying to render up front.

**Comment by bashtech** [comment]
Maybe we display the compilation error to the user if the structure is null or invalid. Divisions can also run into issues if the Twig is invalid and they can't get back to the edit page to correct it.

**Comment by flashadvocate** [comment]
Capturing compile errors was actually the intent but at some point that stopped working. I will say that hopefully in the not so distant future, we will be getting rid of the need for these templates in favor of a more general division structure displayed on the website, so I don't want to spend a great deal of time improving this piece.
