### ISSUE TITLE
Inactive member sorts broken

### ISSUE THREAD

**Issue by flashadvocate** [ClanAODDev/tracker_v3#349]
Sorting via datatables is a challenge because it immediately breaks when words are introduced to numerical sorts.

![image](https://github.com/ClanAODDev/tracker_v3/assets/7848492/c625ef0c-cb1f-4f07-83d8-86b4b075916a)

This is currently happening to the TS / Discord activity. One way which is used in the regular member data rows for division/platoon/squad to get around this is to add columns that get hidden, but are used to sort the visible columns. The downside to that approach is that it means customizing the JS to handle the sort / hiding functionality, which makes it harder to use in multiple places. 

The other option (probably preferable) is to remove the unit of measurement and include that in the column heading instead.

**Comment by bashtech** [comment]
We might be able to use `data-*` attributes to define a sorting value such as the timestamp:

https://datatables.net/manual/data/orthogonal-data#HTML-5

The following seems to work after a quick test:

```
<td data-order="{{ $member->last_voice_activity->timestamp }}">
    <code>{{ $member->present()->lastActive('last_voice_activity', skipUnits: ['weeks','months']) }}</code>
</td>
```

Before (sorting by Discord activity):
![image](https://github.com/ClanAODDev/tracker_v3/assets/112572/6e4625af-a909-4a06-b1f2-a8297a286c9c)

After: 
![image](https://github.com/ClanAODDev/tracker_v3/assets/112572/ebfd7976-8809-40ef-9d97-a9bad6b45e13)

**Comment by flashadvocate** [comment]
Good find. That would be the easiest approach. Might even be worthwhile to move to that instead of sorting by the hidden columns in the other datatables, which requires keeping track of clunky column indexes
