### ISSUE TITLE
Undefined property: Filament\Forms\Components\Select::$pop when creating or editing ticket types

### ISSUE THREAD

**Issue by bashtech** [ClanAODDev/tracker_v3#361]
https://tracker-dev.clanaod.net/admin/ticket-types/create
https://tracker-dev.clanaod.net/admin/ticket-types/1/edit

https://flareapp.io/share/Bm0OJ095

**Comment by flashadvocate** [comment]
57c52c01536932e6b8542e4ab1c18da6ff22b737 fixed this
