### ISSUE TITLE
Prepopulate division settings JSON when creating a division

### ISSUE THREAD

**Issue by bashtech** [ClanAODDev/tracker_v3#363]
Prepopulate a default division settings JSON object when creating a division. Alternatively not make it a required field and generate it during form submission.

**Comment by flashadvocate** [comment]
This is technically already handled since the Division model has a `boot()` method that defines slug and settings during the create processs

**Comment by bashtech** [comment]
It's a required field, so the division cannot be saved until a value other than `null` is specified.

**Comment by flashadvocate** [comment]
I actually ended up removing the settings field entirely from the resource, since we probably won't ever need to manually make changes to it, so it no longer prevents updating or creating new divisions
